### ISSUE TITLE
fitsad method for better fit returned by profile

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#25] opened 2014-11-07 19:18 UTC
Create a fitsad method that gets better fit from profile and run a new fit.

**Comment by andrechalom** [comment] 2015-04-28 20:58
Do you have an example code where this happens? I'm trying to generate a fitsad object that can be "upgraded" by the profile but I'm failing...

Generating a fitsad with some room for improvement...
```R
> set.seed(42)
> data <- rgeom(50, 0.2)
> LL <- function(prob) -sum(dgeom(data, prob, TRUE))
> result <- mle2(LL, start=list(prob=0.75), data=list(data=data), 
+ lower=0.6, upper=1, method="Brent")
```

Now we can profile it to _magically_ discover a better profile:
```R
> profile(result, prof.lower=0)
Profiling has found a better solution,so original fit had not converged:
(new deviance=394.6, old deviance=406.6, diff=-11.96)
Returning better fit ...
Call:
mle2(minuslogl = function (prob) 
-sum(dgeom(data, prob, TRUE)), start = list(prob = 0.600000017459772), 
    method = "Brent", fixed = list(prob = 0.584728315310754), 
    data = list(data = c(2L, 1L, 0L, 2L, 3L, 3L, 2L, 0L, 2L, 
    2L, 0L, 0L, 12L, 0L, 2L, 5L, 0L, 4L, 0L, 2L, 5L, 0L, 0L, 
    5L, 1L, 8L, 9L, 15L, 28L, 5L, 2L, 4L, 0L, 13L, 1L, 2L, 0L, 
    12L, 3L, 0L, 2L, 2L, 0L, 24L, 4L, 1L, 1L, 1L, 4L, 0L)), skip.hessian = TRUE, 
    lower = 0.6, upper = 1, control = list())
Coefficients:
prob.prob 
0.5847283 
Log-likelihood: -197.32 
```

However, this object returned by the profile can't be profiled? I'm not sure what the problem is, and I don't think we can use this object unless we understand better what's going on here.
```R
> new.prof <- profile(result, prof.lower=0)
> profile(new.prof)
Error in pvi[, i] : subscript out of bounds
```

**Comment by andrechalom** [comment] 2015-05-04 19:40
Also: depends on merging #40, as after that we will have distributions with fixed parameters.

**Comment by andrechalom** [comment] 2015-05-04 21:38
Tentative resolution on https://github.com/andrechalom/sads/tree/Fix25, still needs more testing and documenting

**Comment by andrechalom** [comment] 2015-05-07 06:56
PR #45 merged, please test the updatesad function before we close this issue :)

**Comment by andrechalom** [comment] 2015-05-07 07:34
It's specially necessary to test this with volkov, ls or mzsm fits, as I'm not sure if "coef" or "fullcoef" should be used by updatesad.

**Comment by andrechalom** [comment] 2015-05-22 05:09
OK, now I have a working example of this working as intended, instead of the very very artficial example above, and with a distribution that uses fixed parameters:

```R
> set.seed(2)
> data <- round(rexp(20, 0.05))
> (x <- fitmand(data))
Maximum likelihood estimation
Type: discrete rank abundance distribution
Call:
mle2(minuslogl = function (N, s, v) 
-sum(dmand(y, N = N, s = s, v = v, log = TRUE)), start = list(
    s = 2, v = 30), fixed = list(N = 20L), data = list(x = list(
    1, 1, 1, 1, 1, "etc")))
Coefficients:
        N         s         v 
 20.00000  15.00844 106.97356 
Log-likelihood: -1284.08 
```

Well, obviously updatesad crashes. When I tried to see why it crashed, I think I run into some weird bugs from bbmle:
```R
> str(x)
Formal class 'fitrad' [package "sads"] with 16 slots
(...)
  ..@ coef     : Named num [1:2] 15 107
  .. ..- attr(*, "names")= chr [1:2] "s" "v"
  ..@ fullcoef : Named num [1:3] 20 15 107
  .. ..- attr(*, "names")= chr [1:3] "N" "s" "v"
  ..@ vcov     : num [1:2, 1:2] 609 4669 4669 35865
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:2] "s" "v"
  .. .. ..$ : chr [1:2] "s" "v"
> str(profile(x))
Formal class 'mle2' [package "bbmle"] with 12 slots
(...)
  ..@ coef     : Named num 230
  .. ..- attr(*, "names")= chr "v"
  ..@ fullcoef : Named num [1:3] 20 31.1 230
  .. ..- attr(*, "names")= chr [1:3] "N" "s.s" "v"
  ..@ vcov     : logi [1, 1] NA
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr "v"
  .. .. ..$ : chr "v"
``` 

So, for the profile object, both N and s are declared as fixed, and only v is allowed to change. Also, the coefficient names for the "now-fixed" parameters are changed from "name" to "name.name" (s turns s.s and prob turns prob.prob). I wrote a workaround to detect these changes and run a new fit, but this is a bug (or at least a **very** bad design decision) in package bbmle.

**Closed** 2015-05-29 02:14 UTC
Labels: enhancement
