### ISSUE TITLE
Integrity check for classes octav and rad

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#6] opened 2014-07-16 01:18 UTC
Include in the class definitions integrity checks, as no negative values, octave classes and rad abundances ordered and so on.

**Comment by andrechalom** [comment] 2015-04-24 04:44
I am not sure which integrity constants can be declared for these classes. I believe octav has the following restrictions:
```R
octav.valid = function(x){
        if(dim(x)[2] != 3) return("octav objects must have 3 columns")
        if(any(x[,1]!=x[order(x[,1]),1]) | any(x[,2]!=x[order(x[,2]),2])) return("The octav and upper columns of the octav class must be ordered")
        if(any(x[,2] < 0) | any(x[,3] < 0)) return("No negative values are allowed in the upper and Freq columns")
        toi <- function(f) as.numeric(levels(f))[f]
        oc <- x[,1]
        if (is.factor(x[,1])) oc <- toi(oc)
        if(any(abs(x[,2] - 2^oc) > 1e-8)) return("The upper column must be made of powers of the octav column")
        TRUE
}
```
The Freq column can't be required to be integer because of preston octaves, and I don't think we should enforce that all octavs between min() and max() should be present.

**Comment by andrechalom** [comment] 2015-04-26 07:20
Waiting Fix14 to be merged to be sure what classes will be present in the octav classes, but Fix6 is already ready to be merged as well.

**Comment by piklprado** [comment] 2015-04-28 15:32
While checking issue #24 I found a problem with the integrity check for rad :+1: 
```
> teste <- c(1,38,12,2,1,1,6,19,12,5,6,37,1,20,2,5,2,1,21)
> teste.bs <- fitsad(teste, "bs")
> print(radpred(teste.bs)[,1])
Erro em validObject(.Object) (from sads-methods.R#256) : 
  invalid class “rad” object: The abund column of the rad class must be in descending order
```
Back to the drawing board ...

**Comment by andrechalom** [comment] 2015-04-28 17:21
Well, I don't know if we should blame issue #6 or issue #24. What's going on under this error is:
```R
> coef <- as.list(bbmle::coef(teste.bs))
> x <- teste.bs@data$x
> S <- length(x)
> y <- 1:sum(x)
> X <- do.call("pbs", c(list(q = y, lower.tail = F),coef))
> f1 <- approxfun(x=c(1, X), y=c(0, y), method="constant")
> ab <- f1(ppoints(S))
> new("rad", data.frame(rank=1:S, abund=ab))
Error in validObject(.Object) : 
  invalid class “rad” object: The abund column of the rad class must be in descending order
```

But when we inspect "ab", what we find is:
```R
> ab
 [1] NA 33 25 20 17 14 13 11  9  8  7  6  5  4  4  3  2  1  1
> ab[order(-ab)]
 [1] 33 25 20 17 14 13 11  9  8  7  6  5  4  4  3  2  1  1 NA
```

I would say that the validity function is working properly, and the problem is that the rad object containing NA is not a valid object...
```

**Comment by andrechalom** [comment] 2015-04-28 17:32
Anyway, changed it so the example above generates a warning instead of stopping:
```R
> teste <- c(1,38,12,2,1,1,6,19,12,5,6,37,1,20,2,5,2,1,21)
> teste.bs <- fitsad(teste, "bs")
> > radpred(teste.bs)
Object of class "rad"
   rank abund
1     1    NA
2     2    33
3     3    25
4     4    20
5     5    17
6     6    14
7     7    13
8     8    11
9     9     9
10   10     8
11   11     7
12   12     6
13   13     5
14   14     4
15   15     4
16   16     3
17   17     2
18   18     1
19   19     1
Warning message:
In validityMethod(object) : NAs generated in the rad object!!
```

**Comment by piklprado** [comment] 2015-05-05 14:52
Better to keep thi issue open to remind us to change this quicfix when issue we solve #24?

**Closed** 2015-05-21 21:08 UTC
Labels: To do
